vable",
    "rxjs/observable/IfObservable": "rxjs-compat/_esm5/observable/IfObservable",
    "rxjs/observable/GenerateObservable": "rxjs-compat/_esm5/observable/GenerateObservable",
    "rxjs/observable/FromObservable": "rxjs-compat/_esm5/observable/FromObservable",
    "rxjs/observable/FromEventPatternObservable": "rxjs-compat/_esm5/observable/FromEventPatternObservable",
    "rxjs/observable/FromEventObservable": "rxjs-compat/_esm5/observable/FromEventObservable",
    "rxjs/observable/ForkJoinObservable": "rxjs-compat/_esm5/observable/ForkJoinObservable",
    "rxjs/observable/ErrorObservable": "rxjs-compat/_esm5/observable/ErrorObservable",
    "rxjs/observable/EmptyObservable": "rxjs-compat/_esm5/observable/EmptyObservable",
    "rxjs/observable/DeferObservable": "rxjs-compat/_esm5/observable/DeferObservable",
    "rxjs/observable/ConnectableObservable": "rxjs-compat/_esm5/observable/ConnectableObservable",
    "rxjs/observable/BoundNodeCallbackObservable": "rxjs-compat/_esm5/observable/BoundNodeCallbackObservable",
    "rxjs/observable/BoundCallbackObservable": "rxjs-compat/_esm5/observable/BoundCallbackObservable",
    "rxjs/observable/ArrayObservable": "rxjs-compat/_esm5/observable/ArrayObservable",
    "rxjs/observable/ArrayLikeObservable": "rxjs-compat/_esm5/observable/ArrayLikeObservable",
    "rxjs/interfaces": "rxjs-compat/_esm5/interfaces",
    "rxjs/add/operator/zipAll": "rxjs-compat/_esm5/add/operator/zipAll",
    "rxjs/add/operator/zip": "rxjs-compat/_esm5/add/operator/zip",
    "rxjs/add/operator/withLatestFrom": "rxjs-compat/_esm5/add/operator/withLatestFrom",
    "rxjs/add/operator/windowWhen": "rxjs-compat/_esm5/add/operator/windowWhen",
    "rxjs/add/operator/windowToggle": "rxjs-compat/_esm5/add/operator/windowToggle",
    "rxjs/add/operator/wind